@startuml
class guiSharedObject.InputUtility {
- {static} ArrayList<KeyCode> keyPressed
+ {static} boolean getKeyPressed(KeyCode)
+ {static} void setKeyPressed(KeyCode,boolean)
+ {static} void clearKeyPressed()
}


class gui.map.BackgroundImage {
- String imagePath
+ <<Create>> BackgroundImage()
+ void changeWeather(Config.Weather)
+ int getZ()
+ void draw(GraphicsContext)
}


class gui.gameBackground.SunnyBackground {
+ <<Create>> SunnyBackground(double,double)
}

abstract class items.veggies.BaseVeggie {
- boolean isCollected
- float growthPoint
- float MAXGROWTHPOINT
- float growthRate
- float MAXGROWTHRATE
- float Hp
- float waterPoint
- float waterDroppingRate
- float MAXWATERDROPPINGRATE
- float MAXWATER
- int MAXHP
- double width
- double height
+ <<Create>> BaseVeggie(int,float,float,float,int)
+ void spawnOnMap()
+ void collected()
+ boolean isCollected()
+ void weatherEffected()
+ void draw(GraphicsContext)
- void drawGrowthDegree(GraphicsContext)
- void drawBar(GraphicsContext)
+ double getWidth()
+ double getHeight()
+ float getGrowthRate()
+ void setGrowthRate(float)
+ void setCollected(boolean)
+ float getHp()
+ void setHp(float)
+ float getWaterPoint()
+ void setWaterPoint(float)
+ float getGrowthPoint()
+ void setGrowthPoint(float)
+ float getWaterDroppingRate()
+ void setWaterDroppingRate(float)
+ int getMaxHp()
+ float getMaxWater()
}


class items.characters.NormalSlime {
+ <<Create>> NormalSlime()
+ void draw(GraphicsContext)
}

class items.characters.HitHardSlime {
+ <<Create>> HitHardSlime()
+ void draw(GraphicsContext)
}

class items.veggies.RedFlower {
+ <<Create>> RedFlower()
+ void draw(GraphicsContext)
}

class gui.weatherCanvas.RainyCanvas {
- {static} double MAX_SPEED
- {static} int NUM_RAINDROPS
- List<Raindrop> raindrops
+ <<Create>> RainyCanvas()
- void updateRaindrops()
- void render()
}


class gui.weatherCanvas.RainyCanvas$Raindrop {
- double x
- double y
- double speed
- <<Create>> Raindrop()
- void update()
- void render(GraphicsContext)
}


interface items.interfaces.Attackable {
~ void attack()
~ int getAttackRange()
}

class items.characters.Player {
- Broom broom
- Config.WalkState walkState
- boolean isAttack
- int maxAttackCoolDown
+ <<Create>> Player(int,int,int,int,int)
+ void weatherEffected()
+ void attack()
+ void collectVeggie()
+ void action()
+ void walk()
+ void draw(GraphicsContext)
+ int getMaxAttackCoolDown()
+ void setMaxAttackCoolDown(int)
+ Broom getBroom()
+ void setBroom(Broom)
+ Config.WalkState getWalkState()
+ void setWalkState(Config.WalkState)
+ boolean isAttack()
+ void setAttack(boolean)
}


class items.veggies.Daffodil {
+ <<Create>> Daffodil()
+ void draw(GraphicsContext)
}

class gui.map.House {
- String imagePath
+ <<Create>> House(double,double,double,double)
+ int getZ()
+ void changeWeather(Config.Weather)
+ void draw(GraphicsContext)
}


class items.inventories.Clock {
- Config.Weather weather
- int timer
+ <<Create>> Clock()
+ boolean changeSeason(Config.Weather)
+ Config.Weather getWeather()
+ int getTimer()
+ void setTimer(int)
}


class gui.weatherCanvas.WhiteCanvas {
- GraphicsContext gc
- double alpha
- double minSpeed
- double maxSpeed
- double speed
- int level
- double ratioTime
- double speedScaleFactor
+ <<Create>> WhiteCanvas(double,double,int,double)
+ void start()
- void adjustSpeed()
}


class gui.scene.PreStory {
- ArrayList<String> ANALOGS
- int count
- Text analog
- ImageView storyImage
- Button nextButton
- VBox textArea
+ <<Create>> PreStory(GameStarter)
- void setStyle()
- void initializeTextArea()
- void initializeAnalogs()
- void initializeNextButton(GameStarter)
- void showLog(int)
}


interface gui.scene.PreStory$GameStarter {
~ void startGame()
}

class gui.scene.GameScreen {
+ <<Create>> GameScreen(double,double)
+ void addListener()
+ void paintComponent()
}

class gui.scene.Menu {
- Button sunnyButton
- Button snowyButton
- Button rainyButton
- Button creditButton
- Button howToPlayButton
- Button startButton
- Button exitButton
- GridPane creditMenu
- GridPane howToPlayMenu
- HBox weatherButtonContainer
- Text titleText
- VBox titleAndMenu
- StackPane creditHowToPlay
+ <<Create>> Menu(PreStory,Stage)
- void setGridSize()
- void initializeTitleAndMenu()
- void initializeCreditHowToPlay()
- void initializeTitleText()
- void initializeSunnyButton()
- void initializeSnowyButton()
- void initializeRainyButton()
- void initializeWeatherButtonContainer()
- void initializeExitButton(Stage)
- void initializeStartButton(PreStory)
- void initializeHowToButton()
- void initializeHowToMenu()
- void initializeCreditButton()
- void initializeCreditMenu()
- Text getCreditContent()
- void setSunnyBackground()
- void setSnowyBackground()
- void setRainyBackground()
}


interface gui.scene.Menu$PreStory {
~ void preStory()
}

class guiSharedObject.Entity {
# double x
# int z
# boolean visible
# <<Create>> Entity(double,double)
# <<Create>> Entity()
+ double getX()
+ void setX(double)
+ double getY()
+ void setY(double)
+ boolean isDestroyed()
+ boolean isVisible()
+ int getZ()
+ void draw(GraphicsContext)
}


class gui.gameBackground.RainyBackground {
+ <<Create>> RainyBackground(double,double)
}

class guiSharedObject.CollidableEntity {
# double width
# double height
# <<Create>> CollidableEntity(double,double,double,double)
# <<Create>> CollidableEntity()
+ boolean collideWith(double,double,double,double)
+ double getWidth()
+ void setWidth(double)
+ double getHeight()
+ void setHeight(double)
}


class items.characters.SpeedSlime {
+ <<Create>> SpeedSlime()
+ void draw(GraphicsContext)
}

class gui.scene.GameEnd {
- Button startButton
- Button exitButton
- Text endingText
+ <<Create>> GameEnd(GameStarter,Stage)
- void initializeEndingText()
- void initializeStartButton(GameStarter)
- void initializeExitButton(Stage)
}


interface gui.scene.GameEnd$GameStarter {
~ void startGame()
}

class guiSharedObject.RenderableHolder {
- {static} RenderableHolder instance
- List<Entity> backgroundEntities
- List<Entity> entities
- Comparator<Entity> comparator
+ {static} Image witchSprite
+ {static} Image witchWalkSprite
+ {static} Image witchBroomSprite
+ {static} Image witchWalkBroomSprite
+ {static} Image witchAttackSprite
+ {static} Image witchRightSprite
+ {static} Image witchRightBroomSprite
+ {static} Image witchLeftSprite
+ {static} Image witchLeftBroomSprite
+ {static} Image broomSprite
+ {static} Image normalSlimeSprite
+ {static} Image hitHardSlimeSprite
+ {static} Image speedSlimeSprite
+ {static} Image rainbowDrakeIdleSprite
+ {static} Image redFlowerIdleSprite
+ {static} Image daffodilIdleSprite
+ {static} MediaPlayer hitSound
+ {static} MediaPlayer collectSound
+ {static} MediaPlayer clockSound
+ {static} MediaPlayer mainMenuSong
+ {static} MediaPlayer storySong
+ {static} MediaPlayer gameSong
+ <<Create>> RenderableHolder()
+ {static} void loadResource()
+ void add(Entity)
+ void addBackground(Entity)
+ void update()
+ {static} RenderableHolder getInstance()
+ List<Entity> getEntities()
+ List<Entity> getBackgroundEntities()
}


class Main {
- int level
+ {static} void main(String[])
+ void start(Stage)
- void preStory(Stage)
- void endStory(Stage)
- void startGame(Stage)
- void gameEnd(Stage)
- void completeGame(Stage)
}


class items.inventories.Broom {
- boolean isCollected
- float durability
- int attackRange
- float damage
- double width
- double height
+ <<Create>> Broom()
+ void weatherEffected()
+ void collected()
+ void draw(GraphicsContext)
+ void spawnOnMap()
+ void setX(double)
+ void setY(double)
+ double getWidth()
+ double getHeight()
+ float getDamage()
+ void setDamage(float)
+ float getDurability()
+ void setDurability(float)
+ int getAttackRange()
+ void setAttackRange(int)
+ boolean isCollected()
+ void setCollected(boolean)
}


class gui.map.Tree {
- String imagePath
- int option
+ <<Create>> Tree(double,double,double,double,int,int)
+ void changeWeather(Config.Weather)
+ void draw(GraphicsContext)
}


interface items.interfaces.Walkable {
~ float getSpeedRate()
~ void setSpeedRate(float)
~ void walk()
}

class game.GameController {
- {static} GameController instance
- Player player
- ArrayList<Slime> slimeList
- Clock clock
- ArrayList<BaseVeggie> veggiesList
- ArrayList<Broom> broomOnGround
- boolean isGameOver
- int gameTimer
- int maxGameTimer
- BackgroundImage backgroundImage
- House house
- ArrayList<Tree> trees
- ArrayList<Bush> bushes
- SunnyBackground sunnyBackground
- SnowyBackground snowyBackground
- RainyBackground rainyBackground
- int maxRedFlower
- int maxRainbowDrake
- int maxDaffodil
- int redFlowerCount
- int rainbowDrakeCount
- int daffodilCount
- int level
+ <<Create>> GameController()
- void addTree()
- void addBush()
- void initializeWeatherBackground()
+ {static} void play()
- void collectBroom()
- void updateBroom()
- void updateSlime()
- void updateVeggie()
+ void initGames()
+ void getNewVeggie()
+ void getNewSlime()
+ void collectVeggie(BaseVeggie)
+ {static} void deleteVeggie(BaseVeggie)
+ {static} GameController getInstance()
+ void clearStats(int)
- void setStats(int)
- void deleteOldEntity()
+ void startThread()
- void startTimerThread()
- void spawn()
- void updateStats()
- void checkGameOver()
- void startPlayerActionThread()
- void startSlimeWalkThread()
+ boolean isPositionAccesible(double,double,double,double,boolean)
+ int getLevel()
+ int getMaxGameTimer()
+ int getMaxRedFlower()
+ int getMaxRainbowDrake()
+ int getMaxDaffodil()
+ ArrayList<Slime> getSlimeList()
+ Player getPlayer()
+ Clock getClock()
+ ArrayList<BaseVeggie> getVeggiesList()
+ ArrayList<Broom> getBroomOnGround()
+ void setGameover(boolean)
+ boolean isGameOver()
+ int getGameTimer()
+ void setGameTimer(int)
+ House getHouse()
+ BackgroundImage getBackgroundImage()
+ SunnyBackground getSunnyBackground()
+ SnowyBackground getSnowyBackground()
+ RainyBackground getRainyBackground()
+ int getRedFlowerCount()
+ void setRedFlowerCount(int)
+ int getRainbowDrakeCount()
+ void setRainbowDrakeCount(int)
+ int getDaffodilCount()
+ void setDaffodilCount(int)
}


interface items.interfaces.WeatherEffectable {
~ void weatherEffected()
}

class items.veggies.RainbowDrake {
+ <<Create>> RainbowDrake()
+ void draw(GraphicsContext)
}

abstract class items.characters.BaseCharacter {
- float speedRate
- float MAXSPEEDRATE
- int attackRange
- float damage
- int attackCoolDown
+ <<Create>> BaseCharacter(double,double,int,int,float)
+ <<Create>> BaseCharacter(int,int,float)
+ void weatherEffected()
+ void setX(double)
+ void setY(double)
+ int getAttackCoolDown()
+ void setAttackCoolDown(int)
+ float getSpeedRate()
+ void setSpeedRate(float)
+ int getAttackRange()
+ void walk()
+ float getDamage()
+ void setDamage(float)
}


class gui.scene.GamePanel {
- GameController gameController
- GameScreen gameScreen
- StackPane gameScreenWithEffect
- ProgressBar timerBar
- Text clockTimer
- Text gameModeLabel
- Text redFlowerCount
- Text rainbowDrakeCount
- Text daffodilCount
- Text timerText
- int level
- Button sunnyButton
- Button snowyButton
- Button rainyButton
- VBox targetVeggieContainer
- HBox targetVeggie
+ <<Create>> GamePanel(GameController,GameScreen,StackPane,int)
- void addElement()
- void setStyle()
- void initializeClockTimer()
- void initializeTargetVeggie()
- void initializeVeggieCount()
- void initializeTargetVeggieContainer()
- void initializeTimerText()
- void initializeGameModeLabel()
- void initializeWeatherButton()
+ void updateTimerBar(double)
+ void updateClockTimer()
+ void updateVeggieCount()
+ void handleSunnyButton()
+ void handleSnowyButton()
+ void handleRainyButton()
}


class game.Config {
+ {static} int GAMEFRAMEWIDTH
+ {static} int GAMEFRAMEHEIGHT
+ {static} int GAMESCREENWIDTH
+ {static} int GAMESCREENHEIGHT
+ {static} int GAMELABELWIDTH
+ {static} int GAMELABELHEIGHT
+ {static} int WIDTHPERROW
+ {static} int HEIGHTPERROW
+ {static} int GAMETIMER
+ {static} int PLAYERCOLLECTRANGE
+ {static} double PLAYERWIDTH
+ {static} double PLAYERHEIGHT
+ {static} double SLIMEWIDTH
+ {static} double SLIMEHEIGHT
+ {static} int SLIMEMAXSPEEDRATE
+ {static} int SLIMEMINSPEEDRATE
+ {static} int SLIMEMAXDAMAGERANGE
+ {static} float SLIMEWALKSTEP
+ {static} int SLIMEATTACKCOOLDOWN
+ {static} int SLIMESPAWNTIME
+ {static} int PLAYERCOOLDOWNTIME
+ {static} double BROOMWIDTH
+ {static} double BROOMHEIGHT
+ {static} int BROOMMAXDURABILITY
+ {static} int BROOMMINDURABILITY
+ {static} int BROOMMAXATTACKRANGE
+ {static} int BROOMMINATTACKRANGE
+ {static} float BROOMDURABILITYPERATTACK
+ {static} float BROOMDAMAGEPERATTACK
+ {static} int BROOMSPAWNTIME
+ {static} int CLOCKCOOLDOWNTIME
+ {static} double SPAWNLEFTBOUND
+ {static} double SPAWNRIGHTBOUND
+ {static} double SPAWNTOPBOUND
+ {static} double SPAWNBOTTOMBOUND
+ {static} double VEGGIESIZE
}

enum game.Weather {
+  SUNNY
+  SNOWY
+  RAINY
}

enum game.WalkState {
+  STAY
+  FRONT
+  RIGHT
+  LEFT
}

interface gui.map.WeatherChangeable {
~ void changeWeather(Config.Weather)
}

class gui.weatherCanvas.SnowyCanvas {
- {static} int NUM_SNOWFLAKES
- List<Snowflake> snowflakes
+ <<Create>> SnowyCanvas()
- void updateSnowflakes()
- void render()
}


class gui.weatherCanvas.SnowyCanvas$Snowflake {
- double x
- double y
- double speed
- double size
- <<Create>> Snowflake()
- void update()
- void render(GraphicsContext)
}


interface items.interfaces.Collectable {
~ void spawnOnMap()
~ void collected()
~ boolean isCollected()
}

class gui.gameBackground.SnowyBackground {
+ <<Create>> SnowyBackground(double,double)
}

class gui.map.Bush {
- String imagePath
- int option
+ <<Create>> Bush(double,double,double,double,int,int)
+ void changeWeather(Config.Weather)
+ void draw(GraphicsContext)
}


abstract class items.characters.Slime {
- float Hp
- float maxHp
- BaseVeggie targetVeggie
- float maxDamage
+ <<Create>> Slime(int,float,float)
- void spawnOnMap()
+ void weatherEffected()
+ void attack()
+ float getMaxHp()
+ void setMaxHp(float)
+ float getMaxDamage()
+ void setMaxDamage(float)
+ float getHp()
+ void setHp(float)
+ BaseVeggie getTargetVeggie()
+ void setTargetVeggie(BaseVeggie)
+ void walk()
+ void draw(GraphicsContext)
}


class gui.scene.EndStory {
- ArrayList<String> ANALOGS
- int count
- Text analog
- ImageView storyImage
- Button nextButton
- VBox textArea
+ <<Create>> EndStory(GameEnding)
- void setStyle()
- void initializeAnalogs()
- void initializeNextButton(GameEnding)
- void initializeTextArea()
- void showLog(int)
}


interface gui.scene.EndStory$GameEnding {
~ void CompleteGame()
}



gui.map.WeatherChangeable <|.. gui.map.BackgroundImage
guiSharedObject.Entity <|-- gui.map.BackgroundImage
javafx.scene.canvas.Canvas <|-- gui.gameBackground.SunnyBackground
items.interfaces.WeatherEffectable <|.. items.veggies.BaseVeggie
items.interfaces.Collectable <|.. items.veggies.BaseVeggie
guiSharedObject.Entity <|-- items.veggies.BaseVeggie
items.characters.Slime <|-- items.characters.NormalSlime
items.characters.Slime <|-- items.characters.HitHardSlime
items.veggies.BaseVeggie <|-- items.veggies.RedFlower
javafx.scene.canvas.Canvas <|-- gui.weatherCanvas.RainyCanvas
gui.weatherCanvas.RainyCanvas +.. gui.weatherCanvas.RainyCanvas$Raindrop
items.characters.BaseCharacter <|-- items.characters.Player
items.veggies.BaseVeggie <|-- items.veggies.Daffodil
gui.map.WeatherChangeable <|.. gui.map.House
guiSharedObject.CollidableEntity <|-- gui.map.House
javafx.scene.canvas.Canvas <|-- gui.weatherCanvas.WhiteCanvas
gui.scene.GridPane <|-- gui.scene.PreStory
gui.scene.PreStory +.. gui.scene.PreStory$GameStarter
javafx.scene.canvas.Canvas <|-- gui.scene.GameScreen
gui.scene.GridPane <|-- gui.scene.Menu
gui.scene.Menu +.. gui.scene.Menu$PreStory
javafx.scene.canvas.Canvas <|-- gui.gameBackground.RainyBackground
guiSharedObject.Entity <|-- guiSharedObject.CollidableEntity
items.characters.Slime <|-- items.characters.SpeedSlime
javafx.scene.layout.VBox <|-- gui.scene.GameEnd
gui.scene.GameEnd +.. gui.scene.GameEnd$GameStarter
javafx.application.Application <|-- Main
items.interfaces.Collectable <|.. items.inventories.Broom
items.interfaces.WeatherEffectable <|.. items.inventories.Broom
guiSharedObject.Entity <|-- items.inventories.Broom
gui.map.WeatherChangeable <|.. gui.map.Tree
guiSharedObject.CollidableEntity <|-- gui.map.Tree
items.veggies.BaseVeggie <|-- items.veggies.RainbowDrake
items.interfaces.Walkable <|.. items.characters.BaseCharacter
items.interfaces.Attackable <|.. items.characters.BaseCharacter
items.interfaces.WeatherEffectable <|.. items.characters.BaseCharacter
guiSharedObject.CollidableEntity <|-- items.characters.BaseCharacter
gui.scene.HBox <|-- gui.scene.GamePanel
javafx.scene.canvas.Canvas <|-- gui.weatherCanvas.SnowyCanvas
gui.weatherCanvas.SnowyCanvas +.. gui.weatherCanvas.SnowyCanvas$Snowflake
javafx.scene.canvas.Canvas <|-- gui.gameBackground.SnowyBackground
gui.map.WeatherChangeable <|.. gui.map.Bush
guiSharedObject.CollidableEntity <|-- gui.map.Bush
items.characters.BaseCharacter <|-- items.characters.Slime
gui.scene.GridPane <|-- gui.scene.EndStory
gui.scene.EndStory +.. gui.scene.EndStory$GameEnding
@enduml